version: '3.8'

services:
  frontend:
    build: .
    container_name: ics-fe-dev
    working_dir: /app
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    command: ["npm", "run", "start"]
