export const getIncidentTeamData = (data) => [
    { no: 1, position: "Incident Commander", name: data.incident_commander_name, office: data.incident_commander_office_phone, cell: data.incident_commander_mobile_phone },
    { no: 2, position: "Deputy Incident Commander", name: data.deputy_incident_commander_name, office: data.deputy_incident_commander_office_phone, cell: data.deputy_incident_commander_mobile_phone },
    { no: 3, position: "Safety Officer", name: data.safety_officer_name, office: data.safety_officer_office_phone, cell: data.safety_officer_mobile_phone },
    { no: 4, position: "Public Information Officer", name: data.public_information_officer_name, office: data.public_information_officer_office_phone, cell: data.public_information_officer_mobile_phone },
    { no: 5, position: "Liaison Officer", name: data.liaison_officer_name, office: data.liaison_officer_office_phone, cell: data.liaison_officer_mobile_phone },
    { no: 6, position: "Legal Officer", name: data.legal_officer_name, office: data.legal_officer_office_phone, cell: data.legal_officer_mobile_phone },
    { no: 7, position: "Human Capital Officer", name: data.human_capital_officer_name, office: data.human_capital_officer_office_phone, cell: data.human_capital_officer_mobile_phone },
    { no: 8, position: "Operation Section Chief", name: data.operation_section_chief_name, office: data.operation_section_chief_office_phone, cell: data.operation_section_chief_mobile_phone },
    { no: 9, position: "Planning Section Chief", name: data.planning_section_chief_name, office: data.planning_section_chief_office_phone, cell: data.planning_section_chief_mobile_phone },
    { no: 10, position: "Resources Unit Leader", name: data.resources_unit_leader_name, office: data.resources_unit_leader_office_phone, cell: data.resources_unit_leader_mobile_phone },
    { no: 11, position: "Situation Unit Leader", name: data.situation_unit_leader_name, office: data.situation_unit_leader_office_phone, cell: data.situation_unit_leader_mobile_phone },
    { no: 12, position: "Documentation Unit Leader", name: data.documentation_unit_leader_name, office: data.documentation_unit_leader_office_phone, cell: data.documentation_unit_leader_mobile_phone },
    { no: 13, position: "Demobilization Unit Leader", name: data.demobilization_unit_leader_name, office: data.demobilization_unit_leader_office_phone, cell: data.demobilization_unit_leader_mobile_phone },
    { no: 14, position: "Environmental Unit Leader", name: data.environmental_unit_leader_name, office: data.environmental_unit_leader_office_phone, cell: data.environmental_unit_leader_mobile_phone },
    { no: 15, position: "Technical Specialist", name: data.technical_specialist_name, office: data.technical_specialist_office_phone, cell: data.technical_specialist_mobile_phone },
    { no: 16, position: "Logistic Section Chief", name: data.logistic_section_chief_name, office: data.logistic_section_chief_office_phone, cell: data.logistic_section_chief_mobile_phone },
    { no: 17, position: "Communication Unit Leader", name: data.communication_unit_leader_name, office: data.communication_unit_leader_office_phone, cell: data.communication_unit_leader_mobile_phone },
    { no: 18, position: "Medical Unit Leader", name: data.medical_unit_leader_name, office: data.medical_unit_leader_office_phone, cell: data.medical_unit_leader_mobile_phone },
    { no: 19, position: "Food Unit Leader", name: data.food_unit_leader_name, office: data.food_unit_leader_office_phone, cell: data.food_unit_leader_mobile_phone },
    { no: 20, position: "Facilities Unit Leader", name: data.facility_unit_leader_name, office: data.facility_unit_leader_office_phone, cell: data.facility_unit_leader_mobile_phone },
    { no: 21, position: "Supply Unit Leader", name: data.supply_unit_leader_name, office: data.supply_unit_leader_office_phone, cell: data.supply_unit_leader_mobile_phone },
    { no: 22, position: "Transportation Unit Leader", name: data.transportation_unit_leader_name, office: data.transportation_unit_leader_office_phone, cell: data.transportation_unit_leader_mobile_phone },
    { no: 23, position: "Finance Section Chief", name: data.finance_section_chief_name, office: data.finance_section_chief_office_phone, cell: data.finance_section_chief_mobile_phone },
    { no: 24, position: "Procurement Unit Leader", name: data.procurement_unit_leader_name, office: data.procurement_unit_leader_office_phone, cell: data.procurement_unit_leader_mobile_phone },
    { no: 25, position: "Compensation/Claim Unit Leader", name: data.compensation_claim_unit_leader_name, office: data.compensation_claim_unit_leader_office_phone, cell: data.compensation_claim_unit_leader_mobile_phone },
    { no: 26, position: "Cost Unit Leader", name: data.cost_unit_leader_name, office: data.cost_unit_leader_office_phone, cell: data.cost_unit_leader_mobile_phone },
    { no: 27, position: "Time Unit Leader", name: data.time_unit_leader_name, office: data.time_unit_leader_office_phone, cell: data.time_unit_leader_mobile_phone }
]
